In [1]:
from datetime import datetime
from google.cloud import bigquery
from google.oauth2 import service_account
from google.cloud import bigquery
from google.cloud.exceptions import NotFound
import pandas as pd
import yahoo_fin.stock_info as si
from utils.utils_bigquery import *
from datetime import *
import yfinance as yf
import json

In [2]:
key_path = key_path
project = project_id
dataset = 'bronze'
table = 'bronze_ticker_recommendations'
table_conca = f'{project}.{dataset}.{table}'

In [3]:
# Conectamos con Bigquery
bigquery = BigQueryUtils(key_path)

In [4]:
unique_tickers = get_unique_tickers()

In [5]:
import yfinance as yf
import pandas as pd

data = []

for _, row in unique_tickers.iterrows():
    ticker = row['ticker']  # Corregir el nombre de la columna para acceder al ticker

    try:
        # Obtener datos históricos
        data_row = yf.Ticker(ticker).recommendations

        # Agregar el ticker como una columna en los datos históricos
        data_row['ticker'] = ticker

        data_row['date'] = date.today()

        # Añadir los datos a la lista
        data.append(data_row)
        print(f"Datos obtenidos para {ticker}.")
    except Exception as e:
        print(f"Error al obtener datos para {ticker}: {e}")

# Concatenar todos los DataFrames en uno solo
df = pd.concat(data, ignore_index=True)
df

Datos obtenidos para AAPL.
Datos obtenidos para AMGN.
Datos obtenidos para AMZN.
Datos obtenidos para AXP.
Datos obtenidos para BA.
Datos obtenidos para CAT.
Datos obtenidos para CRM.
Datos obtenidos para CSCO.
Datos obtenidos para CVX.
Datos obtenidos para DIS.
Datos obtenidos para DOW.
Datos obtenidos para GS.
Datos obtenidos para HD.
Datos obtenidos para HON.
Datos obtenidos para IBM.
Datos obtenidos para INTC.
Datos obtenidos para JNJ.
Datos obtenidos para JPM.
Datos obtenidos para KO.
Datos obtenidos para MCD.
Datos obtenidos para MMM.
Datos obtenidos para MRK.
Datos obtenidos para MSFT.
Datos obtenidos para NKE.
Datos obtenidos para PG.
Datos obtenidos para TRV.
Datos obtenidos para UNH.
Datos obtenidos para V.
Datos obtenidos para VZ.
Datos obtenidos para WMT.

    period  strongBuy  buy  hold  sell  strongSell ticker        date
0       0m         11   21     6     0           0   AAPL  2024-08-16
1      -1m         12   19    12     1           0   AAPL  2024-08-16
2      -2m         10   19    13     1           0   AAPL  2024-08-16
3      -3m         10   24     7     1           0   AAPL  2024-08-16
4       0m          3    7    15     0           0   AMGN  2024-08-16
..     ...        ...  ...   ...   ...         ...    ...         ...
115    -3m          2    5    19     2           1     VZ  2024-08-16
116     0m          8    7    15     1           1    WMT  2024-08-16
117    -1m         11   26     3     0           0    WMT  2024-08-16
118    -2m         12   24     4     0           0    WMT  2024-08-16
119    -3m         11   20     8     0           0    WMT  2024-08-16

[120 rows x 8 columns]

In [6]:
# Convertimos las columnas period y date a string para que bigquery lo guarde
df['period'] = df['period'].astype(str)
df['date'] = df['date'].astype(str)

In [8]:
# Guardamos los datos en bigquery
bigquery.save_dataframe(df, project, dataset, table, if_exists='replace', schema=None)

100%|██████████| 1/1 [00:00<?, ?it/s]